[] => 
	type => expression_statement
	expression => 
		type => binary_expression
		right_expression => 
			type => parenthesis_expression
			expression => 
				type => binary_expression
				right_expression => 
					value => 2
					type => number_value
				operator => ^
				line_number => 4
				left_expression => 
					value => 2
					type => number_value
		operator => *
		line_number => 2
		left_expression => 
			type => binary_expression
			right_expression => 
				value => 3
				type => number_value
			operator => +
			line_number => 1
			left_expression => 
				type => binary_expression
				right_expression => 
					value => 2
					type => number_value
				operator => +
				line_number => 1
				left_expression => 
					value => 1
					type => number_value
good
